# Generated by Django 6.0.2 on 2026-03-03 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_jobseekerprofile_recruiterprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobseekerprofile',
            name='full_name',
        ),
        migrations.AddField(
            model_name='jobseekerprofile',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='jobseekerprofile',
            name='experience',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='jobseekerprofile',
            name='skills',
            field=models.TextField(blank=True),
        ),
    ]
