# Generated by Django 6.0.2 on 2026-03-07 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_jobseekerprofile_full_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseekerprofile',
            name='full_name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
